---

- name: install firewalld
  yum:
    name: firewalld
    state: present

- name: start firewalld and enable at boot
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: enable and persist http allowed services
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: enable and persist https allowed services
  firewalld:
    service: https
    permanent: yes
    state: enabled
    immediate: yes

- name: enable and persist extra port
  firewalld:
    port: "{{ FIREWALLD_EXTRA_PORT }}"
    permanent: yes
    state: enabled
    immediate: yes
