---

- name: install python3
  yum:
    name: python3

- name: install virtualenv
  pip:
    name: virtualenv
    executable: pip3

- name: install git
  yum:
    name: git

- name: install the 'Development tools' package group needed to install psycopg2
  yum:
    name: "@Development tools"
