---

- name: create the webapp group
  group:
    name: webapp
    state: present

- name: create the webapp user
  user:
    name: webapp
    group: webapp

- name: clone the sr-dispersal repository
  become: yes
  become_user: webapp
  git:
    repo: "https://github.com/vbuens/sr-dispersal.git"
    dest: /home/webapp/sr-dispersal
    update: no

- name: install gunicorn
  become: yes
  become_user: webapp
  pip:
    name: gunicorn
    virtualenv: /home/webapp/venv
    virtualenv_command: /usr/local/bin/virtualenv
    

- name: install sr-dispersal requirements
  become: yes
  become_user: webapp
  pip:
    requirements: /home/webapp/sr-dispersal/requirements.txt
    virtualenv: /home/webapp/venv
    virtualenv_command: /usr/local/bin/virtualenv
